---
abstract: 'An object to manage running things in parallel processes.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Exception::LessClever: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-Runner
provides:
  Parallel::Runner:
    file: lib/Parallel/Runner.pm
    version: 0.006
requires:
  POSIX: 0
  Time::HiRes: 0
resources:
  bugtracker: http://github.com/exodist/Parallel-Runner/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Parallel-Runner
version: 0.006
